import type { Metadata } from "next";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/footer/Footer";
import { auth } from "@/auth.config";
import { redirect } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  // console.log({ session });

  if (session?.user) {
    redirect("/");
  }

  return (
    <>
      <main className="flex flex-col justify-center items-center bg-primary min-h-screen">
        <div className="w-full sm:w-[350px] px-10">{children}</div>
      </main>
    </>
  );
}
