import type { Metadata } from "next";
import { fontBody, fontHeading } from "@/config/fonts";
import Providers from "./providers/Providers";
import { ToastContainer } from "react-toastify";
import { GoogleAnalytics, CookieConsent } from "@/components";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fontBody.variable} ${fontHeading.variable}`}>
        <Providers>
          {children}
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
          <CookieConsent />
          <GoogleAnalytics />
        </Providers>
      </body>
    </html>
  );
}
