import type { Metadata } from "next";
import { fontBody, fontHeading } from "@/config/fonts";
import Providers from "./providers/Providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fontBody.variable} ${fontHeading.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
