import type { Metadata } from 'next'
import { Navbar } from '@/src/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function PublicLayout({ children }: { children: React.ReactNode }) {
    return (
        <>
            <Navbar />
            <main className="flex flex-col">
                { children }
            </main>
        </>
    )
}